services:
  - type: web
    name: urban-transport-api
    runtime: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_ATLAS_URL
        sync: false
      - key: SPARK_OUTPUT
        value: /tmp/spark-output